/**
 * Swiss city labels for the basemap. Generated by scripts/build-basemap.ts
 * from Natural Earth (public domain) — do not edit by hand.
 */
export type City = { name: string; lon: number; lat: number; rank: number };

export const CITIES: City[] = [
  {
    name: 'Genève',
    lon: 6.14,
    lat: 46.21,
    rank: 1,
  },
  {
    name: 'Zürich',
    lon: 8.5481,
    lat: 47.3819,
    rank: 2,
  },
  {
    name: 'Bern',
    lon: 7.467,
    lat: 46.9167,
    rank: 4,
  },
  {
    name: 'Basel',
    lon: 7.59,
    lat: 47.5804,
    rank: 7,
  },
  {
    name: 'Lausanne',
    lon: 6.65,
    lat: 46.5304,
    rank: 7,
  },
  {
    name: 'Luzern',
    lon: 8.28,
    lat: 47.0504,
    rank: 7,
  },
  {
    name: 'Lugano',
    lon: 8.9667,
    lat: 46.0004,
    rank: 7,
  },
  {
    name: 'Biel',
    lon: 7.25,
    lat: 47.1666,
    rank: 8,
  },
  {
    name: 'Chur',
    lon: 9.5,
    lat: 46.85,
    rank: 8,
  },
  {
    name: 'St. Gallen',
    lon: 9.362,
    lat: 47.423,
    rank: 10,
  },
  {
    name: 'Schaffhausen',
    lon: 8.633,
    lat: 47.706,
    rank: 10,
  },
  {
    name: 'Fribourg',
    lon: 7.15,
    lat: 46.8,
    rank: 10,
  },
  {
    name: 'Neuchâtel',
    lon: 6.923,
    lat: 46.999,
    rank: 10,
  },
  {
    name: 'Sion',
    lon: 7.354,
    lat: 46.239,
    rank: 10,
  },
  {
    name: 'Zug',
    lon: 8.487,
    lat: 47.179,
    rank: 10,
  },
  {
    name: 'Frauenfeld',
    lon: 8.9049,
    lat: 47.5526,
    rank: 10,
  },
  {
    name: 'Bellinzona',
    lon: 9.02,
    lat: 46.197,
    rank: 10,
  },
  {
    name: 'Aarau',
    lon: 8.034,
    lat: 47.39,
    rank: 10,
  },
  {
    name: 'Herisau',
    lon: 9.2833,
    lat: 47.3833,
    rank: 10,
  },
  {
    name: 'Solothurn',
    lon: 7.537,
    lat: 47.212,
    rank: 10,
  },
  {
    name: 'Schwyz',
    lon: 8.648,
    lat: 47.02,
    rank: 10,
  },
  {
    name: 'Liestal',
    lon: 7.737,
    lat: 47.483,
    rank: 10,
  },
  {
    name: 'Delémont',
    lon: 7.345,
    lat: 47.37,
    rank: 10,
  },
  {
    name: 'Sarnen',
    lon: 8.243,
    lat: 46.899,
    rank: 10,
  },
  {
    name: 'Altdorf',
    lon: 8.638,
    lat: 46.879,
    rank: 10,
  },
  {
    name: 'Stans',
    lon: 8.3833,
    lat: 46.95,
    rank: 10,
  },
  {
    name: 'Glarus',
    lon: 9.0667,
    lat: 47.05,
    rank: 10,
  },
  {
    name: 'Appenzell',
    lon: 9.4167,
    lat: 47.3333,
    rank: 10,
  },
];
